version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current

    steps:
	- checkout

	- run:
		name: deps
		command: make deps
	- run:
		name: lint
		command: make lint

	- run:
        	name: test
          	command: make test

	- run:
		name: docker_build
		command: make docker_build
      
	- run:
		name: docker_push
		command: make docker_push

workflows:
  basic:
    jobs:
      - build-and-test